### ISSUE TITLE
isAxios error

### ISSUE THREAD

**Issue by oksanassss** [bcgov/vc-authn-oidc#134] opened 2021-09-26 13:29 UTC
after the scan QR code I have error. 
isAxiosError.js:10 GET https://8ead-95-70-244-247.ngrok.io/vc/connect/poll?pid=af9fd457-d177-45fb-9281-f5e48e0f581b 400

**Comment by esune** [comment] 2021-09-26 19:37
This is the expected behaviour: you will receive a 400 request as the page polls the controller for a presentation request that does not yet exist.

**Comment by oksanassss** [comment] 2021-10-02 11:12
how can ı add  verified user for get datas after  the QRcode ?

**Comment by esune** [comment] 2021-10-03 17:06
How did you configure your proof-request? See [this comment](https://github.com/bcgov/vc-authn-oidc/issues/133#issuecomment-930303026) for tips on configuring your proof request.

**Comment by esune** [comment] 2021-10-03 17:07
Closing as it looks like you have opened #135.

**Closed by esune** 2021-10-03 17:07 UTC
