### ISSUE TITLE
Issues authenticating with ACM using the Accredited Lawyer with BC Person Credential proof request

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/vc-authn-oidc#328] opened 2023-09-06 14:32 UTC
Issues reported by CSB, and affecting 5 or 6 people over the weekend and late last week despite having both credentials in their wallets.

Associated error seen in the logs:
```
cannot be validated: Timestamp on sub-proof #1 is missing vs. requested attribute group 5fa9cca8-53f3-4b6f-aefb-ad46cbab381e
```

Proof showing the `null` timestamp:
```
"requested_proof": {
    "revealed_attrs": {},
    "revealed_attr_groups": {
        "a936c0da-3b29-454d-b402-6cddf7707047": {
            "sub_proof_index": 0,
            "values": {
                "Member Status": {
                    "raw": "Practising",
                    "encoded": "80773232418251071324168107671111183860898849021300637818611153951738456909662"
                },
                "PPID": {
                    "raw": "MC12346",
                    "encoded": "113284298158317279834285630941508089008702590104135140037200578623010622754530"
                },
                "Member Status Code": {
                    "raw": "PRAC",
                    "encoded": "102521883305815317207776104318259002335679112657360890741484805658633694808310"
                },
                "Given Name": {
                    "raw": "Brian",
                    "encoded": "39388102679383361046384283256767693264694536157469555220500653620124394466245"
                },
                "Surname": {
                    "raw": "Goodrangsy",
                    "encoded": "46068774144900373535655915149122223034843140238303904857222880961861409369635"
                }
            }
        },
        "5fa9cca8-53f3-4b6f-aefb-ad46cbab381e": {
            "sub_proof_index": 1,
            "values": {
                  ...
                },
                  ...          
                }
            }
        }
    },
    "self_attested_attrs": {},
    "unrevealed_attrs": {},
    "predicates": {}
},
"identifiers": [
    {
        "schema_id": "4xE68b6S5VRFrKMMG1U95M:2:Member Card:1.5.1",
        "cred_def_id": "4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default",
        "rev_reg_id": "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:4ae1cc6c-f6bd-486c-8057-88f2ce74e960",
        "timestamp": 1693953937
    },
    {
        "schema_id": "RGjWbW1eycP7FrMf4QJvX8:2:Person:1.0",
        "cred_def_id": "RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person",
        "rev_reg_id": "RGjWbW1eycP7FrMf4QJvX8:4:RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person:CL_ACCUM:6a1fa86a-f5b2-4b26-ac94-ae165a63da10",
        "timestamp": null
    }
]
```

**Comment by WadeBarnes** [comment] 2023-09-06 14:43
The vc-authn agents have been using the same configuration and aca-py version (`0.7.3-rc0`) since Nov 18, 2022.
The vc-authn controllers have been using the same configuration and version since May 10, 2022.

**Comment by WadeBarnes** [comment] 2023-09-06 14:54
Some questions:
- Is Michael setup with TestFlight, can he revert to the previous wallet version and test?
- When (with which version of the BC Wallet) did Michael receive his person credential?
- Could this be an issue with BC Wallet version `1.0.10 Build 1097`, or and issue when upgrading to `1.0.10 Build 1097` when you already have the credentials?
  - Based in the results the issue only affects some users of `1.0.10 Build 1097`.  We don't know if other versions are affected.

**Comment by cvarjao** [comment] 2023-09-06 15:46
* Michal is setup to use teflight, but he is not using builds from testflight atm
* From Michael:
    > person credential was long time ago, I don't think I've ever had to re-issue that one, so before the upgrade [to 1.0.10]
* It could, that would be an issue with either Askar and/or AFJ

Q: what is that `timestamp` field used for? is that part of proof of non revocation?

**Comment by swcurran** [comment] 2023-09-06 15:50
Yes — it is the identifier for the specific RevRegEntry used by the holder to construct the non-revocation proof.

Could be something in AFJ version related to the upgrade to AnonCreds RS?  Is there a difference in AFJ versions between what the user is using and what Clecio used?

**Comment by cvarjao** [comment] 2023-09-06 16:44
I am still unable to reproduce the error:
- I've uninstalled my BC Wallet App, and installed at 1.0.9
- Got Lawyer Credential
- Got Person Credential
- Tried to login to ACM, and it works as expected.
- Upgrade the app to 1.0.10
- Tried to login to ACM, and it works as expected.

**Comment by WadeBarnes** [comment] 2023-09-06 17:17
This is what a successful request contains (note no `timestamp` attributes):
```
"requested_proof": {
    "revealed_attrs": {},
    "revealed_attr_groups": {
        "935a40d6-1a13-4764-9cf7-43a18ebdb54e": {
            "sub_proof_index": 1,
            "values": {
                "given_names": {
                    ...
                },
                "family_name": {
                    ...
                }
            }
        },
        "c3241c36-2eae-4b0f-a5a2-b052fbbc36e3": {
            "sub_proof_index": 0,
            "values": {
                "Surname": {
                    "raw": "Goodrangsy",
                    "encoded": "46068774144900373535655915149122223034843140238303904857222880961861409369635"
                },
                "Given Name": {
                    "raw": "Alex",
                    "encoded": "99262857098057710338306967609588410025648622308394250666849665532448612202874"
                },
                "PPID": {
                    "raw": "MC12348",
                    "encoded": "1333347123958091868677147927491789918780284402440175294640196150783619529829"
                },
                "Member Status Code": {
                    "raw": "PRAC",
                    "encoded": "102521883305815317207776104318259002335679112657360890741484805658633694808310"
                },
                "Member Status": {
                    "raw": "Practising",
                    "encoded": "80773232418251071324168107671111183860898849021300637818611153951738456909662"
                }
            }
        }
    },
    "self_attested_attrs": {},
    "unrevealed_attrs": {},
    "predicates": {}
},
"identifiers": [
    {
        "schema_id": "4xE68b6S5VRFrKMMG1U95M:2:Member Card:1.5.1",
        "cred_def_id": "4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default",
        "rev_reg_id": "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:4ae1cc6c-f6bd-486c-8057-88f2ce74e960"
    },
    {
        "schema_id": "RGjWbW1eycP7FrMf4QJvX8:2:Person:1.0",
        "cred_def_id": "RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person",
        "rev_reg_id": "RGjWbW1eycP7FrMf4QJvX8:4:RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person:CL_ACCUM:6a1fa86a-f5b2-4b26-ac94-ae165a63da10"
    }
]
```

**Comment by WadeBarnes** [comment] 2023-09-06 17:22
Also seeing other requests containing this style of content:
```
"identifiers": [
    {
        "schema_id": "4xE68b6S5VRFrKMMG1U95M:2:Member Card:1.5.1",
        "cred_def_id": "4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default",
        "rev_reg_id": "4xE68b6S5VRFrKMMG1U95M:4:4xE68b6S5VRFrKMMG1U95M:3:CL:59232:default:CL_ACCUM:4ae1cc6c-f6bd-486c-8057-88f2ce74e960",
        "timestamp": null
    },
    {
        "schema_id": "RGjWbW1eycP7FrMf4QJvX8:2:Person:1.0",
        "cred_def_id": "RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person",
        "rev_reg_id": "RGjWbW1eycP7FrMf4QJvX8:4:RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person:CL_ACCUM:6a1fa86a-f5b2-4b26-ac94-ae165a63da10",
        "timestamp": null
    }
]
```

**Comment by jleach** [comment] 2023-09-06 17:43
So if I'm readint this right its being rejected because there is a timestamp associated with a revocable credential?

```
        "schema_id": "4xE68b6S5VRFrKMMG1U95M:2:Member Card:1.5.1",
        "timestamp": 1693953937
```

As per the docs:

```text
Timestamp for Irrevocable Credential
A presentation's inclusion of a timestamp pertaining to an irrevocable credential evinces tampering: the verifier MUST reject such a presentation.
```

**Comment by esune** [comment] 2023-09-06 17:46
> 
> As per the [docs](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0441-present-proof-best-practices#timestamp-for-irrevocable-credential):
> 
> Timestamp for Irrevocable Credential A presentation's inclusion of a timestamp pertaining to an irrevocable credential evinces tampering: the verifier MUST reject such a presentation.

This is for `IRrevocable` credentials - non-revocable. Both credentials in the proof are revocable.

**Comment by jleach** [comment] 2023-09-06 17:48
@esune Ok, so it does not like the that the timestamp is missing on a revocable credential:

```
        "schema_id": "RGjWbW1eycP7FrMf4QJvX8:2:Person:1.0",
        "timestamp": null
```

**Missing Timestamp**
A presentation with no timestamp for a revocable credential purporting to satisfy a requested item in the corresponding presentation request, where the requested item has an applicable non-revocation interval, evinces tampering: the verifier MUST reject such a presentation.

**Comment by swcurran** [comment] 2023-09-06 18:01
Theory — the wallet (AFJ) is not able to get the revocation registry but is going ahead with constructing the proof for what it has.  Perhaps the person is behind a firewall that is preventing Indy access, but because they have the data other than the revocation registry, they are able to create the proof.

If the person is willing — perhaps try with the wallet on mobile data and not on wifi?

**Comment by cvarjao** [comment] 2023-09-06 18:33
I will check which network is being used and report back

**Comment by cvarjao** [comment] 2023-09-06 19:05
Using Wifi, or just cellular data results in the same problem

**Comment by cvarjao** [comment] 2023-09-06 23:01
Getting a new person credential seems to have resolved the problem. However, some of the people reporting the problem are new users, so their credentials are fresh. I've asked CSB to monitor and report back

**Comment by esune** [comment] 2023-11-06 16:44
@cvarjao did you get any more new reports about this? If not, given teh fact this is reported for 1.0 and we'er moving to 2.0 I'd close and see if we need to reopen in the future again.

**Comment by cvarjao** [comment] 2023-11-06 17:36
The root cause is still unknown, but we haven't seen any new reports. So we can close it.

**Closed by cvarjao** 2023-11-06 17:36 UTC
Labels: 1.0
