### ISSUE TITLE
Detect the difference between mobile camera app or digital wallet app QR code scans

### ISSUE THREAD

**Issue by knguyenBC** [bcgov/vc-authn-oidc#234] opened 2023-03-09 17:10 UTC
**User story:**
As a user, I want to be informed that I need to scan the QR code using a digital wallet after I have scanned it using my mobile camera app so that I can be informed of correct steps and course correct.

The server that is responding to what is sent after the scanning of the QR code should be able to detect the difference between the wallet and web browser/camera responding.

The BCSC app does something similar. Users are directed to [this page](https://id.gov.bc.ca/static/selfsetup.html) when a QR code is scanned by a camera app instead of the BCSC app.

**Comment by knguyenBC** [comment] 2023-03-09 17:10
@swcurran

**Comment by esune** [comment] 2023-03-09 17:37
I am not sure this is doable: whoever is exposing the QR code is just putting it out there for consumption, there is no interaction with the mobile wallet until the QR code is scanned and it goes and tries to fetch the data (proof request) at the link.

This will likely be something that COULD be embedded in the mobile OS in the future, if the wallet was built-in, similarly to how the camera extension (Google Lens and/or whatever is used in iOS) is able to detect a URL and open the browser.

**Comment by swcurran** [comment] 2023-03-09 17:54
Let’s discuss this, Emiliano. I can’t be a wallet feature — it is a web page from the controller. My thought is that if the component displaying the QR code (which is usually the controller — e.g. vc-authn-oidc, but other controllers as well) can detect if the wallet scanned and responded vs. the camera/web browser responded.  If the controller can detect the difference, then the response can be a web page (help page) vs. wallet (DIDComm messaging).

**Comment by esune** [comment] 2023-03-09 18:15
I kind-of disagree: if the phone camera (with the QR-scanning plugin, a regular camera does not do anything) scans a QR code with a URL and the phone does not have a browser installed and registered as a handler for URLs, the problem is exactly the same. And the user does not get any prompt about having to install a browser. 

That being said, I agree we should sit down and see if we can "work around" this somehow. The only thing I am thinking *might* be doable is to *watch* the URL serving the payload, detect what user agent the request is coming from and redirect to a different target (help page/DIDcomm message) depending on whether the request comes from a browser or from an unrecognized user agent (I do not know whether the wallet provides on - @amanji @jleach any insight?). If the mobile wallet uses the built-in OS web browser to fetch the URL we are back to square one since the user agent would not be unset or unique.

Assuming the above worked, it would be good to standardize the behaviour so that ALL wallets meet the user agent requirements to have this working.

**Comment by swcurran** [comment] 2023-03-09 18:36
The intention of this task is to research exactly that and see if we can do something useful.  What can the server side do to recognize the the different situations and if it can recognize the difference, respond accordingly.

Evidently BC Services Card Mobile App is doing something similar, so it makes sense that we might be able to do something as well.

BTW — if the QR content is a protocol handler for the wallet, the camera could/would pass control to the wallet app and life would be good. However, we run into the same problem with that as with text link (URL) protocol handlers on iOS — that it doesn’t allow the registration of apps to be a handler of protocols.

**Comment by esune** [comment] 2023-03-09 18:56
The QR code is a shortened URL that causes a redirect to the long URl with the handler as query parameter, so the first step is always a browser GET.

Not sure what the interaction in BC Services Card is, I'll investigate to get more context.

**Comment by jleach** [comment] 2023-03-09 22:17
The wallet does not open the URL when its scanned. It just decodes the payload `?oob=...` and uses that to find the mediator. Does not even matter if the URL part is real or not. You could just put up a catch-all web page on the URL that says "this QR code is meand to be scanned with a digital wallet. Here is a link to the BC Wallet" and it'll just work.

**Comment by swcurran** [comment] 2023-03-09 22:24
Right — that’s good. So if a camera browses the URL and tries to resolve it, the server would know it is not the wallet and could, as you say, display a catch-all screen.  So that should be easy to document and use in vc-authn-oidc.

However, there is the use case where the URL is shortened, the wallet does have to resolve it to get redirected to the real URL.  In that case, can the URL Shortner handler detect the difference between the wallet and the camera/browser resolving the URL?

vc-authn-oidc uses the shortened URL approach.

**Comment by jleach** [comment] 2023-03-09 22:43
> Right — that’s good. So if a camera browses the URL and tries to resolve it, the server would know it is not the wallet and could, as you say, display a catch-all screen. So that should be easy to document and use in vc-authn-oidc.

Yup

> However, there is the use case where the URL is shortened, the wallet does have to resolve it to get redirected to the real URL. In that case, can the URL Shortner handler detect the difference between the wallet and the camera/browser resolving the URL?

I think the url service will just do a redirect (HTTP 30x) so I suspect the end result will be the same for the browser. I would need to test how the wallet deals with a redirect. I think it would notice the URL is missing the payload `c_i=` or `oob=` and that would make it freak out a little. Again, because it does not care about the URL, just the Query-string payload.

**Comment by swcurran** [comment] 2023-03-09 22:57
> I think the url service will just do a redirect (HTTP 30x) so I suspect the end result will be the same for the browser. I would need to test how the wallet deals with a redirect. 

If the wallet is using any vc-authn-oidc service, it is happily handling a redirect. What we need to see is the log from the service handling the wallet and handling the camera/browser.

**Comment by esune** [comment] 2023-06-01 10:33
Resolved by #273

**Closed by esune** 2023-06-01 10:33 UTC
Labels: 2.0
