### ISSUE TITLE
error :  unauthorized_client

### ISSUE THREAD

**Issue by oznfc** [bcgov/vc-authn-oidc#143] opened 2021-11-30 14:09 UTC
I added new client . when ı authenticated the app I'm getting error : 
```
   https://af65-31-223-51-97.ngrok.io/connect/token 400
   unauthorized_client
```
```
 const settings = {
      silentRedirectUri: 'http://localhost:3000/silent-renew.html',
      authority: 'https://af65-31-223-51-97.ngrok.io',
      client_id: 'react-oidc-demo',
      client_secret: 'react-oidc-demo',
      redirect_uri: 'http://localhost:3000/signin-callback.html',
      response_type: 'code',
      scope: 'openid profile vc_authn',
      automaticSilentRenew: true,
      // RequireClientSecret: false,
      silent_redirect_uri: 'http://localhost:3000/silent-renew.html',
      post_logout_redirect_uri: 'http://localhost:3000',
      userStore: new WebStorageStateStore({ store: window.localStorage }),
      extraQueryParams: {
        pres_req_conf_id: 'verified-email'
      },
      metadata: {
        issuer: 'https://af65-31-223-51-97.ngrok.io',
        authorization_endpoint: 'https://af65-31-223-51-97.ngrok.io/vc/connect/authorize',
        token_endpoint: 'https://af65-31-223-51-97.ngrok.io/vc/connect/token',
        userinfo_endpoint: 'https://af65-31-223-51-97.ngrok.io/vc/connect/userinfo',
        jwks_uri: 'https://af65-31-223-51-97.ngrok.io/.well-known/openid-configuration/jwks',
        end_session_endpoint: 'http://localhost:3000'
      },
      loadUserInfo: false
    };
```
https://af65-31-223-51-97.ngrok.io  is  localhost:5000

**Comment by oznfc** [comment] 2021-11-30 18:43
it's console logs 
```
[18:41:01 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
controller_1      | [18:41:01 DBG] Start token request.
controller_1      | [18:41:01 DBG] Start client validation
controller_1      | [18:41:01 DBG] Start parsing Basic Authentication secret
controller_1      | [18:41:01 DBG] Start parsing for secret in post body
controller_1      | [18:41:01 DBG] Parser found secret: PostBodySecretParser
controller_1      | [18:41:01 DBG] Secret id found: react-oidc-demo
controller_1      | [18:41:01 DBG] react-oidc-demo found in database: True
controller_1      | [18:41:01 DBG] client configuration validation for client react-oidc-demo succeeded.
controller_1      | [18:41:01 DBG] Public Client - skipping secret validation success
controller_1      | [18:41:01 DBG] Client validation success
controller_1      | [18:41:01 INF] {"ClientId": "react-oidc-demo", "AuthenticationMethod": "SharedSecret", "Category": "Authentication", "Name": "Client Authentication Success", "EventType": "Success", "Id": 1010, "Message": null, "ActivityId": "0HMDK5NCMA8LQ:00000004", "TimeStamp": "2021-11-30T18:41:01.0000000Z", "ProcessId": 8, "LocalIpAddress": "::ffff:172.24.0.7:80", "RemoteIpAddress": "31.223.51.97", "$type": "ClientAuthenticationSuccessEvent"}
controller_1      | [18:41:01 DBG] Start token request validation
controller_1      | [18:41:01 DBG] Start validation of authorization code token request
controller_1      | [18:41:01 ERR] Client not authorized for code flow, {"ClientId": "react-oidc-demo", "ClientName": "react-oidc-demo", "GrantType": "authorization_code", "Scopes": null, "AuthorizationCode": "********", "RefreshToken": "********", "UserName": null, "AuthenticationContextReferenceClasses": null, "Tenant": null, "IdP": null, "Raw": {"client_id": "react-oidc-demo", "client_secret": "***REDACTED***", "code": "50d2518b-9601-4334-b6aa-638065e51ed5", "redirect_uri": "http://localhost:3000/signin-callback.html", "code_verifier": "ceae180fe6e341a691410fca0fffcdb1858f8fe3151a46b2a74d9165a3ae597931c34a4fbe314fbfbe6298957c79eb5a", "grant_type": "authorization_code"}, "$type": "TokenRequestValidationLog"}
controller_1      | [18:41:01 INF] {"ClientId": "react-oidc-demo", "ClientName": "react-oidc-demo", "RedirectUri": null, "Endpoint": "Token", "SubjectId": null, "Scopes": null, "GrantType": "authorization_code", "Error": "unauthorized_client", "ErrorDescription": null, "Category": "Token", "Name": "Token Issued Failure", "EventType": "Failure", "Id": 2001, "Message": null, "ActivityId": "0HMDK5NCMA8LQ:00000004", "TimeStamp": "2021-11-30T18:41:01.0000000Z", "ProcessId": 8, "LocalIpAddress": "::ffff:172.24.0.7:80", "RemoteIpAddress": "31.223.51.97", "$type": "TokenIssuedFailureEvent"}

```

**Comment by oznfc** [comment] 2021-12-02 14:18
ı solved client error. 
```
  | [14:13:58 DBG] client configuration validation for client react-oidc-demo succeeded.
controller_1      | [14:13:58 DBG] Public Client - skipping secret validation success
controller_1      | [14:13:58 DBG] Client validation success
controller_1      | [14:13:58 INF] {"ClientId": "react-oidc-demo", "AuthenticationMethod": "NoSecret", "Category": "Authentication", "Name": "Client Authentication Success", "EventType": "Success", "Id": 1010, "Message": null, "ActivityId": "0HMDLINHOPU7M:00000008", "TimeStamp": "2021-12-02T14:13:58.0000000Z", "ProcessId": 8, "LocalIpAddress": "::ffff:172.26.0.6:80", "RemoteIpAddress": "31.223.51.97", "$type": "ClientAuthenticationSuccessEvent"}
```

but ı have new error .  
```
CORS request made for path: /vc/connect/userinfo from origin: http://localhost:3000 but was ignored because path was not for an allowed IdentityServer CORS endpoint
```
already added to database(ClientCorsOrigins) it  ı can't solve cors error.  it's  chrome error : 
```
Access to XMLHttpRequest at 'https://18a2-31-223-51-97.ngrok.io/vc/connect/userinfo' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
store.js?c0d6:34 OIDC error {context: 'authenticateOidcPopup', error: 'Network Error'}
App.vue?234e:38 I am listening to the oidc oidcError event in vuex-oidc {context: 'authenticateOidcPopup', error: 'Network Error'}
oidc-client.min.js?dd17:1 GET https://18a2-31-223-51-97.ngrok.io/vc/connect/userinfo net::ERR_FAILED
```

**Comment by esune** [comment] 2021-12-02 16:50
> ı solved client error.

What was the fix for this? Was it just a configuration that needed to be tweaked?

> 
> but ı have new error .
> 
> ```
> CORS request made for path: /vc/connect/userinfo from origin: http://localhost:3000 but was ignored because path was not for an allowed IdentityServer CORS endpoint
> ```
> 
> already added to database(ClientCorsOrigins) it ı can't solve cors error. it's chrome error :
> 
> ```
> Access to XMLHttpRequest at 'https://18a2-31-223-51-97.ngrok.io/vc/connect/userinfo' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> store.js?c0d6:34 OIDC error {context: 'authenticateOidcPopup', error: 'Network Error'}
> App.vue?234e:38 I am listening to the oidc oidcError event in vuex-oidc {context: 'authenticateOidcPopup', error: 'Network Error'}
> oidc-client.min.js?dd17:1 GET https://18a2-31-223-51-97.ngrok.io/vc/connect/userinfo net::ERR_FAILED
> ```

What you did seems correct to me. Maybe double check the URL of the window making the call, it looks like you may be using the auth popup rather than a redirect and I wonder if that has maybe a slightly different URL than the base app.

**Comment by oznfc** [comment] 2021-12-05 09:02
I closed  ```userinfo_endpoint``` line. I cant see token and my credential data in my client. But ı want to ask is it normal ? My ```access_token``` is invalid ,  ```state ``` and  ```refresh_token``` is undefined. 
![Ekran Görüntüsü - 2021-12-05 11-47-19](https://user-images.githubusercontent.com/39590206/144740321-0682794f-73ce-4777-a1ed-bbd21a34b584.jpg)

**Comment by esune** [comment] 2021-12-06 17:04
This is by design: vc-authn is state-less and therefore it is not possible (at least with the current implementation/design) to also provide authentication/authorization tokens to clients. To do this, you should instead use it as an Identity Provider connected to an AIM system such as Keycloak: this way, after the authentication step completed by calling vc-authn, the AIM system will take care of managing the lifecycle of the OIDC tokens.

**Comment by oznfc** [comment] 2021-12-08 11:37
Ok , I understood. I want to ask a more  question . When I  login first time I can login successfully with ```Verified Credential Access``` button.(QR).  But when ı tried secont time.  I have error :
```User with email mymail@gmail.com already exists. Please login to account management to link the account. ``` . 
I don't want to login with email and password  ,  ı want to login only secont option so  Qr code.  is it possible ?

**Comment by esune** [comment] 2021-12-08 18:02
The warning `User with email mymail@gmail.com already exists. Please login to account management to link the account.` is due to a setting in Keycloak that does not allow for duplicate email addresses. I think it can be fixed by disabling `login with email` in the real settings (see screenshot):
![image](https://user-images.githubusercontent.com/2395873/145259931-ff1966d3-42f6-47da-88df-de8acabbb7a5.png)

To only use the QR code you would have to disable the other identity providers in the realm settings as well.

**Comment by oznfc** [comment] 2021-12-09 08:32
what is your keycloak version ?   when I tried this way like screenshot I 'm getting ```invalid username or password``` error.

**Comment by oznfc** [comment] 2021-12-09 13:16
I added new flow to my identy provider. 
![image](https://user-images.githubusercontent.com/39590206/145403241-2a801ea8-fdcb-4d8f-ba1d-642a3f2cf380.png)
now ı can login with qr.

**Comment by esune** [comment] 2021-12-09 16:48
> what is your keycloak version ? when I tried this way like screenshot I 'm getting `invalid username or password` error.

The version I was using was 12.0.2 (outdated now, I know).

**Comment by esune** [comment] 2021-12-21 17:26
Closing the issue as it appears to be resolved. Please reopen if required.

**Closed by esune** 2021-12-21 17:26 UTC
